---
inputdirs: 
    - /fast/users/szyskam_c/work/NGSData/AMLNHLMiSeq2/fastq
workdir: /fast/users/szyskam_c/scratch/develop/Vali2 # here your results are created
envs: env # the folder of the env-files (MacOS requires different environments)
samples: # here go all your samples
    samplesheet: info/AMLNHL_list.xlsx # excel file containing sample name, mutation position and MutID (either abspath or relative to snakedir)
    umi_barcode: false # suffix for the fastq containing the umi-barcode
setup:
    library: NebNext  # have to be found at bed_files/SureSelect/<build>/SS_<library_version>_<build>_<Padded | Covered>[_nochr].bed
    library_version: 1.2
    platform: illumina
    Flowcell: Standard
    Instrument: MiSeq
    platform_unit: A00643.HKCN3DRXX
    UMI: false  # if UMI information should be used in pipeline
#### CUSTOM TOOLS ############
paths:
    mystatic: /fast/groups/ag_damm/work/ref/
    bihstatic: /fast/projects/cubit/current/static_data
    scripts: scripts/ # folder relative to snakedir
    filter_settings: /fast/users/szyskam_c/snakes/projects/somVarWES/info
#### REF SECTION ###############
ref:
    build: hg38
    hg38:
        genome_path: genome/gatk/hg38/
        genome: genome/gatk/hg38/hg38.fasta
        genome_split: genome/gatk/hg38/split
        dbsnp: annotation/gatk/hg38/dbsnp_138.hg38.vcf
        dbsnp_all: annotation/gatk/hg38/All_20180418.vcf
        dbsnp_common: annotation/gatk/hg38/common_all_20180418.vcf
        gold_standard_indels: annotation/gatk/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf
        phase1k_indels: annotation/gatk/hg38/1000G_phase1.snps.high_confidence.hg38.vcf
        bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
#### TOOLS SECTION ##############
tools:
    gatk: gatk # 
    gatk3: java -jar /fast/users/szyskam_c/work/utils/gatk3.8/GenomeAnalysisTK.jar -T
fastq:
    threads: 20
ubamXT:
    threads: 8
    use_jdk: true # use_jdk_in/deflater to avoid SIGSEV error
alignment:
    tool: bwa
    threads: 16
    clip_overlap: false
    strategy: MostDistant  # alignment strategy for MergeBamAlignment
    use_jdk: true
bamindex:
    threads: 2
tag_bam: # needs enough RAM for loading entire uncompressed index fastq into memory
    run: true
    max_mem: 30g # memory for java VM (30g seems neccessary - needs to be smaller than threads * vmem/thread)
merge_bam:
    threads: 20
resplit_bam:
    threads: 6
dedup:
    threads: 4
dedup_umi:
    max_mem: 10g
    keep_dups: true # keep dups if you want to perform UMI-correction
realignGATK:
    threads: 16
recalib:
    run: true
    threads: 12
    known_sites: dbsnp_common   # which dbsnp database to use beside gold_standard_indels and phase1k
UMI_filter:
    run: false # if false and setup-->UMI is true, run umi-dedup
    min_reads:  1 # for WES-data, 1 is good; for targeted >3  counts for all fgbio tools
    group:
        threads: 10
        mem: 2G
        group_strategy: adjacency
        min_base_Q: 20
        min_map_q: 20
        edits: 1  # 1 edit in a umi-node should be ok
    call:
        threads: 6
        mem: 6G
        error_rate_pre_umi: 45
        error_rate_post_umi: 40
        min_input_Q: 20 # input base quality (10 is default; IDT says 30)
    remap:
        threads: 10
        mem: 6G
        clip_overlap: true
        clip_adapters: true
    filter:
        threads: 6
        mem: 6G
        max_error_rate_per_read: 0.05
        max_error_rate_per_base: 0.1
        min_Q: 30 # input base quality
        max_no_call: 0.1 # fraction of reads filtered per M/e
VAFdetect:
    remove_dups: false
    Q: 25   # base quality
    MAPQ: 20 # -q in pileup
    threads: 6
    minVAF: 0 # minimum VAF for VAF output
    minDepth: 5
targetCov:
    padding: 25 # how many bases around InsertRange is considered target
    MAPQ: 20 # -q in pileup
    rolling_window: 10
    threads: 5
    minCov: 10  # minimum coverage for output
    remove_dups: false
offTarget:
    maxDist: 37 # find the gaps where adjacent distance is greater maxDist
    minCov: 100 # find regions offTarget with coverage > minCov